### ISSUE TITLE
Urls for media assets

### ISSUE THREAD

**Issue by AdamBCo** [twilio/twilio-chat-ios#10]
I understand that I can retrieve Message Media Content via the following [instructions](https://www.twilio.com/docs/chat/media-support#retrieving-message-media-content), but is it possible to get a url for the media asset instead?

If not, can you please provide instructions on how to generate a Twilio url so that my client applications can take advantage of Async Image downloaders like PINRemoteImage, Kingfisher, and Nuke?

Do you have plans to support urls in the future?

**Comment by Gray-Wind** [comment]
You can send a usual message with an url as it contents and in attributes define that it is a media message. When you receive such a message with those specific attributes, you can display it as a media message.

**Comment by Gray-Wind** [comment]
We have plans to expose Twilio url as it already done for [JS SDK](https://media.twiliocdn.com/sdk/js/chat/releases/3.3.3/docs/Media.html#getContentUrl__anchor), but no ETA known.

**Comment by Gray-Wind** [comment]
I totally forgot to mention that last versions of SDK has method [`getMediaContentTemporaryUrlWithCompletion:`](https://media.twiliocdn.com/sdk/ios/chat/releases/4.0.2/docs/Classes/TCHMessage.html#//api/name/getMediaContentTemporaryUrlWithCompletion:).
