### ISSUE TITLE
App crash when starting and finishing TwillioChatClient

### ISSUE THREAD

**Issue by ZivKes** [twilio/twilio-chat-ios#11]
App crashing when calling init() and finishing rapidly

`ThreadedExecutor5@0x2838316f8 (78)#0	0x00000001c30b70dc in __pthread_kill ()
#1	0x00000001c3130094 in pthread_kill$VARIANT$mp ()
#2	0x00000001c300fea8 in abort ()
#3	0x00000001c26dc788 in abort_message ()
#4	0x00000001c26dc830 in default_terminate_handler() ()
#5	0x00000001c26e8838 in std::__terminate(void (*)()) ()
#6	0x00000001c26e88bc in std::terminate() ()
#7	0x00000001c26cff70 in std::__1::thread::~thread() ()
#8	0x000000010765b5d0 in std::__1::allocator<std::__1::thread>::destroy(std::__1::thread*) [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1860
#9	0x000000010765b5cc in void std::__1::allocator_traits<std::__1::allocator<std::__1::thread> >::__destroy<std::__1::thread>(std::__1::integral_constant<bool, true>, std::__1::allocator<std::__1::thread>&, std::__1::thread*) [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1727
#10	0x000000010765b5cc in void std::__1::allocator_traits<std::__1::allocator<std::__1::thread> >::destroy<std::__1::thread>(std::__1::allocator<std::__1::thread>&, std::__1::thread*) [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1595
#11	0x000000010765b5cc in std::__1::__vector_base<std::__1::thread, std::__1::allocator<std::__1::thread> >::__destruct_at_end(std::__1::thread*) [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:413
#12	0x000000010765b5bc in std::__1::__vector_base<std::__1::thread, std::__1::allocator<std::__1::thread> >::clear() [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:356
#13	0x000000010765b5bc in std::__1::__vector_base<std::__1::thread, std::__1::allocator<std::__1::thread> >::~__vector_base() at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/vector:441
#14	0x0000000107756978 in std::__1::vector<std::__1::thread, std::__1::allocator<std::__1::thread> >::~vector() [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iterator:1425
#15	0x0000000107756970 in std::__1::vector<std::__1::thread, std::__1::allocator<std::__1::thread> >::~vector() [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iterator:1425
#16	0x0000000107756970 in rtd::ThreadedExecutor::Impl::~Impl() at /Users/distiller/rtd-cpp-shared-lib/Source/Common/ThreadedExecutor.cpp:56
#17	0x0000000107656d24 in std::__1::__shared_count::__release_shared() [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3490
#18	0x0000000107656cfc in std::__1::__shared_weak_count::__release_shared() [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3532
#19	0x0000000107656cfc in std::__1::shared_ptr<rtd::ThreadedExecutor::Impl>::~shared_ptr() at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4468
#20	0x000000010774f6bc in std::__1::shared_ptr<rtd::ThreadedExecutor::Impl>::~shared_ptr() [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4466
#21	0x000000010774f6b8 in rtd::ThreadedExecutor::~ThreadedExecutor() [inlined] at /Users/distiller/rtd-cpp-shared-lib/Interface/Common/ThreadedExecutor.h:27
#22	0x000000010774f6a8 in rtd::ThreadedExecutor::~ThreadedExecutor() at /Users/distiller/rtd-cpp-shared-lib/Interface/Common/ThreadedExecutor.h:27
#23	0x000000010761e9f4 in std::__1::__shared_count::__release_shared() [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3490
#24	0x000000010761e9cc in std::__1::__shared_weak_count::__release_shared() [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:3532
#25	0x000000010761e9cc in std::__1::shared_ptr<rtd::ITMChannels>::~shared_ptr() at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4468
#26	0x0000000107634f88 in std::__1::shared_ptr<rtd::ThreadedExecutor>::~shared_ptr() [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:4466
#27	0x0000000107634f84 in ::-[TwilioChatClient .cxx_destruct]() at /Users/distiller/rtd-sdk-chat-ios/ChatClient/Sources/ChatClient/TwilioChatClient.mm:84
#28	0x00000001c26f27cc in object_cxxDestructFromClass(objc_object*, objc_class*) ()
#29	0x00000001c27026b8 in objc_destructInstance ()
#30	0x00000001c2702720 in object_dispose ()
#31	0x000000010762b1e4 in ::-[TwilioChatClient dealloc]() at /Users/distiller/rtd-sdk-chat-ios/ChatClient/Sources/ChatClient/TwilioChatClient.mm:624
#32	0x000000010769c524 in auto rtd::TMClient::onClientSynchronization(rtd::TMClientSynchronization)::$_11::operator()(std::__1::weak_ptr<rtd::ITMClientListener>) const::'lambda'(auto)::operator()<std::__1::shared_ptr<rtd::ITMClientListener> >(auto) const [inlined] at /Users/distiller/rtd-cpp-chat-lib/Source/TMClient.cpp:362
#33	0x000000010769c510 in decltype(fp0(std::declval<std::__1::shared_ptr<auto> >())) rtd::visit<rtd::ITMClientListener, rtd::TMClient::onClientSynchronization(rtd::TMClientSynchronization)::$_11::operator()(std::__1::weak_ptr<rtd::ITMClientListener>) const::'lambda'(auto)>(std::__1::weak_ptr<auto> const&, rtd::TMClient::onClientSynchronization(rtd::TMClientSynchronization)::$_11::operator()(std::__1::weak_ptr<rtd::ITMClientListener>) const::'lambda'(auto)&&) [inlined] at /Users/distiller/rtd-cpp-chat-lib/target/dependency/ios/rtd-shared-lib/include/Common/Visit.h:14
#34	0x000000010769c4e0 in rtd::TMClient::onClientSynchronization(rtd::TMClientSynchronization)::$_11::operator()(std::__1::weak_ptr<rtd::ITMClientListener>) const [inlined] at /Users/distiller/rtd-cpp-chat-lib/Source/TMClient.cpp:361
#35	0x000000010769c4e0 in decltype(std::__1::forward<rtd::TMClient::onClientSynchronization(rtd::TMClientSynchronization)::$_11&>(fp)(std::__1::forward<std::__1::weak_ptr<rtd::ITMClientListener> >(fp0))) std::__1::__invoke<rtd::TMClient::onClientSynchronization(rtd::TMClientSynchronization)::$_11&, std::__1::weak_ptr<rtd::ITMClientListener> >(rtd::TMClient::onClientSynchronization(rtd::TMClientSynchronization)::$_11&, std::__1::weak_ptr<rtd::ITMClientListener>&&) [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:4428
#36	0x000000010769c4d8 in void std::__1::__invoke_void_return_wrapper<void>::__call<rtd::TMClient::onClientSynchronization(rtd::TMClientSynchronization)::$_11&, std::__1::weak_ptr<rtd::ITMClientListener> >(rtd::TMClient::onClientSynchronization(rtd::TMClientSynchronization)::$_11&, std::__1::weak_ptr<rtd::ITMClientListener>&&) [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__functional_base:349
#37	0x000000010769c4d8 in std::__1::__function::__func<rtd::TMClient::onClientSynchronization(rtd::TMClientSynchronization)::$_11, std::__1::allocator<rtd::TMClient::onClientSynchronization(rtd::TMClientSynchronization)::$_11>, void (std::__1::weak_ptr<rtd::ITMClientListener>)>::operator()(std::__1::weak_ptr<rtd::ITMClientListener>&&) at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:1562
#38	0x000000010769d4cc in std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>::operator()(std::__1::weak_ptr<rtd::ITMClientListener>) const [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:1913
#39	0x000000010769d4b4 in decltype(std::__1::forward<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&>(fp)(std::__1::forward<std::__1::weak_ptr<rtd::ITMClientListener>&>(fp0))) std::__1::__invoke<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&>(std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&) [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:4428
#40	0x000000010769d48c in std::__1::__bind_return<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>, std::__1::tuple<std::__1::weak_ptr<rtd::ITMClientListener> >, std::__1::tuple<>, __is_valid_bind_return<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>, std::__1::tuple<std::__1::weak_ptr<rtd::ITMClientListener> >, std::__1::tuple<> >::value>::type std::__1::__apply_functor<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>, std::__1::tuple<std::__1::weak_ptr<rtd::ITMClientListener> >, 0ul, std::__1::tuple<> >(std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::tuple<std::__1::weak_ptr<rtd::ITMClientListener> >&, std::__1::__tuple_indices<0ul>, std::__1::tuple<>&&) [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:2216
#41	0x000000010769d48c in std::__1::__bind_return<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>, std::__1::tuple<std::__1::weak_ptr<rtd::ITMClientListener> >, std::__1::tuple<>, __is_valid_bind_return<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>, std::__1::tuple<std::__1::weak_ptr<rtd::ITMClientListener> >, std::__1::tuple<> >::value>::type std::__1::__bind<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&>::operator()<>() [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/functional:2249
#42	0x000000010769d48c in void boost::asio::asio_handler_invoke<std::__1::__bind<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&> >(std::__1::__bind<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&>&, ...) [inlined] at /Users/distiller/rtd-cpp-chat-lib/target/dependency/ios/include/boost/asio/handler_invoke_hook.hpp:69
#43	0x000000010769d48c in void boost_asio_handler_invoke_helpers::invoke<std::__1::__bind<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&>, std::__1::__bind<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&> >(std::__1::__bind<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&>&, std::__1::__bind<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&>&) [inlined] at /Users/distiller/rtd-cpp-chat-lib/target/dependency/ios/include/boost/asio/detail/handler_invoke_helpers.hpp:37
#44	0x000000010769d48c in void boost::asio::detail::handler_work<std::__1::__bind<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&>, boost::asio::system_executor>::complete<std::__1::__bind<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&> >(std::__1::__bind<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&>&, std::__1::__bind<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&>&) [inlined] at /Users/distiller/rtd-cpp-chat-lib/target/dependency/ios/include/boost/asio/detail/handler_work.hpp:82
#45	0x000000010769d48c in boost::asio::detail::completion_handler<std::__1::__bind<std::__1::function<void (std::__1::weak_ptr<rtd::ITMClientListener>)>&, std::__1::weak_ptr<rtd::ITMClientListener>&> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) at /Users/distiller/rtd-cpp-chat-lib/target/dependency/ios/include/boost/asio/detail/completion_handler.hpp:70
#46	0x0000000107750470 in boost::asio::detail::scheduler_operation::complete(void*, boost::system::error_code const&, unsigned long) [inlined] at /Users/distiller/rtd-cpp-shared-lib/target/dependency/ios/include/boost/asio/detail/scheduler_operation.hpp:40
#47	0x000000010775045c in boost::asio::detail::strand_service::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) at /Users/distiller/rtd-cpp-shared-lib/target/dependency/ios/include/boost/asio/detail/impl/strand_service.ipp:168
#48	0x0000000107753960 in boost::asio::detail::scheduler_operation::complete(void*, boost::system::error_code const&, unsigned long) [inlined] at /Users/distiller/rtd-cpp-shared-lib/target/dependency/ios/include/boost/asio/detail/scheduler_operation.hpp:40
#49	0x0000000107753948 in boost::asio::detail::scheduler::do_run_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&) at /Users/distiller/rtd-cpp-shared-lib/target/dependency/ios/include/boost/asio/detail/impl/scheduler.ipp:401
#50	0x00000001077520fc in boost::asio::detail::scheduler::run(boost::system::error_code&) at /Users/distiller/rtd-cpp-shared-lib/target/dependency/ios/include/boost/asio/detail/impl/scheduler.ipp:154
#51	0x00000001077542fc in boost::asio::io_context::run() [inlined] at /Users/distiller/rtd-cpp-shared-lib/target/dependency/ios/include/boost/asio/impl/io_context.ipp:62
#52	0x00000001077542e4 in rtd::ThreadedExecutor::Impl::process_events() [inlined] at /Users/distiller/rtd-cpp-shared-lib/Source/Common/ThreadedExecutor.cpp:144
#53	0x00000001077542e4 in rtd::ThreadedExecutor::Impl::init_threads(unsigned long, rtd::ThreadedExecutor const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0::operator()() const [inlined] at /Users/distiller/rtd-cpp-shared-lib/Source/Common/ThreadedExecutor.cpp:180
#54	0x00000001077541c0 in decltype(std::__1::forward<rtd::ThreadedExecutor::Impl::init_threads(unsigned long, rtd::ThreadedExecutor const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0>(fp)()) std::__1::__invoke<rtd::ThreadedExecutor::Impl::init_threads(unsigned long, rtd::ThreadedExecutor const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0>(rtd::ThreadedExecutor::Impl::init_threads(unsigned long, rtd::ThreadedExecutor const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0&&) [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/type_traits:4428
#55	0x00000001077541c0 in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, rtd::ThreadedExecutor::Impl::init_threads(unsigned long, rtd::ThreadedExecutor const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, rtd::ThreadedExecutor::Impl::init_threads(unsigned long, rtd::ThreadedExecutor const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0>&, std::__1::__tuple_indices<>) [inlined] at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:342
#56	0x00000001077541c0 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, rtd::ThreadedExecutor::Impl::init_threads(unsigned long, rtd::ThreadedExecutor const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)::$_0> >(void*) at /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/thread:352
#57	0x00000001c31392c0 in _pthread_body ()
#58	0x00000001c3139220 in _pthread_start ()
#59	0x00000001c313ccdc in thread_start ()
`

**Comment by Gray-Wind** [comment]
Hi! What is the version of the framework?

**Comment by ZivKes** [comment]
This happens in all versions above 2.5.0, i was using 2.6.5 but checked all versions.
The last version on which this crash does not happen is 2.5.0

**Comment by Gray-Wind** [comment]
Could you provide us logs?
You could set up a level of logs before client creation with
```objc
[TwilioChatClient setLogLevel:TCHLogLevelTrace];
```

**Comment by Gray-Wind** [comment]
This crash should be fixed in 2.6.6.
