### ISSUE TITLE
Can't get Reachability feature to work

### ISSUE THREAD

**Issue by miktav** [twilio/twilio-chat-ios#15]
I'm trying to enhance my chat feature to show which users are online.

I've followed the instructions to enable reachability on my chat instance, but I'm not seeing any users detected as online.

Here is the code I've tried. It returns the _correct_ users for the channel, but shows `isOnline` status as **false** for all users, even when some users are online.

    chatClient.users()?.userDescriptors(for: twilioChannel, completion: { (result, paginator) in
        if result.isSuccessful(), let p = paginator {
            var users = ""
            for item in p.items() {
                let user = "\(item.identity!) online? \( item.isOnline())"
                users += user + "\n"
            }
            completion(Result.success(users))
        }
    })

**Comment by berkus** [comment]
> Indicates whether the user is online. Note that if TwilioChatClient indicates reachability is not enabled, this will return NO.

Have you checked that `[TwilioChatClient isReachabilityEnabled]` returns TRUE?

**Comment by miktav** [comment]
Yes, it does. I have run my app simultaneously on a device and two simulator instances, logged in as 3 different users. The app in each case says that reachability is enabled, but that all users are not online.

**Comment by miktav** [comment]
This code does work:

    chatClient.users()?.subscribedUser(withIdentity: "MIKE", completion: { (result, user) in
        if result.isSuccessful(), let user = user {
            let text = "\(user.identity!) online? \( user.isOnline())"
            print(text)
            completion(Result.success(text))
            return
        }
    })

In this case, I'm getting a `TCHUser` object. The code I posted previously gets `TCHUserDescriptor` objects. Both objects have an `isOnline` property.

**Comment by Gray-Wind** [comment]
Which version of SDK do you use?
Could you provide us logs with reproduction of this issue?

**Comment by miktav** [comment]
We are using 2.6.5. Where would you like me to send logs? They include our Account SID and other private stuff.

When calling the `userDescriptors` method, the logs show the correct "is_online" value, but the items in `paginator.items()` don't return it in the `isOnline()` method.

**Comment by Gray-Wind** [comment]
Open a ticket with logs here: twilio.com/support then post number of your ticket here, I will take a look at it.

2.6.5 already included fix for online status in user descriptors.

**Comment by miktav** [comment]
The problem is definitely resolved in 2.6.6, so I am closing this issue.

I noticed in my logs that I was running 2.6.4. This seemed odd since my cartfile.resolved said "v2.6.5". Anyhow, after running carthage update, I was updated to 2.6.6 and all is well. Thank you for your help!

**Comment by berkus** [comment]
Ahh, good to know @miktav, because this was definitely fixed in 2.6.5 and this report caused a few odd looks around here.
