### ISSUE TITLE
Please provide an XCFramework and a binary package manifest for SwiftPM. 

### ISSUE THREAD

**Issue by bwhiteley** [twilio/twilio-chat-ios#16]
https://developer.apple.com/videos/play/wwdc2020/10147/

**Comment by berkus** [comment]
Hi, yes, it is going to be added, but not instantly.

**Comment by tomhut** [comment]
This would be great, having an XCFramework available (through SPM or otherwise) is the main thing blocking us from launching a Mac Catalyst app.

**Comment by bwhiteley** [comment]
Any updates on this? With Xcode 12 released today, some folks will be keen on switching to SwiftPM soon.

**Comment by Gray-Wind** [comment]
This issue is on our roadmap. We will keep you updated.

**Comment by borut-t** [comment]
Any progress on SPM @Gray-Wind ?

**Comment by berkus** [comment]
@borut-t I believe this work will continue next year. Currently we have some other releases on our hands.

**Comment by borut-t** [comment]
Great. I hope we can have it soon.

**Comment by CorbinMontague** [comment]
+1 We consume this framework and `twilio-accessmanager-ios`, and neither seem to support the ability for Carthage to create an xcframework using [this](https://github.com/Carthage/Carthage/pull/3071) PR that should hopefully get merged soon. Without supporting SPM as an alternative installation method, the only way we can seem to use this dependency with Xcode 12.3 (now that it added additional checks around universal binaries) is by manually pulling it into our code base.

**Comment by mruvim** [comment]
+1

**Comment by mmdumi** [comment]
Latest master in Carthage allows for compiling projects as xcframeworks.
Can you please provide an updated version of the twilio ios sdk as xcframework ?
Thank you

**Comment by Gray-Wind** [comment]
@CorbinMontague Hello, there is no need to use `twilio-accessmanager-ios`, it is deprecated. All needed events you can receive right from frameworks.

@mmdumi We have it in our plans. We target to deliver XCFramework in Q1 if nothing more important would come.

**Comment by berkus** [comment]
Hi,

XCFramework versions (with MacCatalyst support) are prepared and pending release. We will update here with the version numbers once released.

**Comment by Gray-Wind** [comment]
I am happy to announce that we finally provided an XCFramework and it could be distributed with SPM.

But we did not add support for Mac Catalyst just yet. If you want to participate in piloting for Mac Catalyst support you can create a ticket, leave a comment here or [contact support](https://support.twilio.com/hc/en-us/requests/new).
