### ISSUE TITLE
Project is not building with carthage 0.35.0

### ISSUE THREAD

**Issue by Siemian** [twilio/twilio-chat-ios#17]
Cartfile:
```
github "twilio/twilio-chat-ios"
```
Running command:
```
carthage bootstrap --platform iOS --no-use-binaries
```
Produces error:
```
*** Checking out twilio-chat-ios at "v3.1.1"
*** xcodebuild output can be found in /*****/carthage-xcodebuild.CmiCbu.log
*** Skipped building twilio-chat-ios due to the error:
Dependency "twilio-chat-ios" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/twilio/twilio-chat-ios/issues/new
```

**Comment by berkus** [comment]
Does it work when you skip `--no-use-binaries` option?

**Comment by Siemian** [comment]
If there is available binary on github that is compatible it will work.

**Comment by berkus** [comment]
SDK does not have non-binary artifacts. So it works only if you allow using binaries.

**Comment by Siemian** [comment]
Due to one issue in carthage https://github.com/Carthage/Carthage/issues/2711 downloading binaries does not work on our CI. Because `API rate limit exceeded for` error is produced(even when github token is available).

**Comment by Gray-Wind** [comment]
@Siemian Have you solved the issue with building your app?

**Comment by Siemian** [comment]
For now we moved Twilio dependency to cocoapods, not ideal, but works.

**Comment by Gray-Wind** [comment]
Glad to hear that.

From our side we cannot do anything as our SDK only distributed in binary form and with use of `--no-use-binaries` Carthage won't be able do download it.

I'm closing this ticket as there is no possible action form our side.

**Comment by Siemian** [comment]
Actually, i just realized, you could use a `binary` option, which is designed for frameworks like yours https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#binary-only-frameworks

**Comment by Gray-Wind** [comment]
Fantastic found! Thanks for sharing.
