### ISSUE TITLE
TCHMember vs TCHUser attributes

### ISSUE THREAD

**Issue by miktav** [twilio/twilio-chat-ios#18]
This is a question about the framework, not an issue.

Are custom attributes assigned to a TCHMember stored separately from those assigned to the corresponding TCHUser? In other words, can TCHMember attributes be used to store information about the user that are unique to that user's membership in a specific channel?

**Comment by berkus** [comment]
Hi @miktav 

You are correct, Users' and Members' attributes are separated.
