### ISSUE TITLE
Users Online/Offline Status at Runtime

### ISSUE THREAD

**Issue by kansal2403** [twilio/twilio-chat-ios#19]
Guys I want to update the Users Online/Offline Status at Runtime, But
No delegate function Is being called when any member from the Channel leaves the chat or joins the Chat
i.e When client.shutdown() method is called from any member's side.

**Comment by berkus** [comment]
Leaving or joining a Chat channel does not affect user's online status.

Your service instance should have user reachability enabled [in configuration](https://www.twilio.com/docs/chat/reachability-indicator) to propagate user online/offline status events.

**Comment by kansal2403** [comment]
@berkus Thanks for reply but its still not working for me.
I have updated the Service Settings, please check the screen shot
https://prnt.sc/ue80lb

**Comment by berkus** [comment]
@kansal2403 ok, so when you subscribe to the user via getAndSubscribeUser and that user goes offline, you don't receive his online status updates?

Could you please share the detailed logs?

**Comment by berkus** [comment]
No logs provided, closing.
