### ISSUE TITLE
xcode 10 builds

### ISSUE THREAD

**Issue by jamezilla** [twilio/twilio-chat-ios#2]
Are there any plans to get Xcode 10 Swift 4.2 builds out? The Apple event is in 2 weeks, which likely means Xcode 10 GM and iOS 12 general availability.

**Comment by rbeiter** [comment]
Hi @jamezilla - we've tested our builds with Xcode 10, Swift 4.2, and iOS 12 and our latest releases are compatible.  Are you seeing any issues consuming them?

**Comment by rbeiter** [comment]
Closing this one out, I see we've been in contact through Twilio support as well and that issue is resolved.  Please let us know if we can assist you further.
