### ISSUE TITLE
No Podspec for 4.0.2

### ISSUE THREAD

**Issue by mitchtreece** [twilio/twilio-chat-ios#20]
Noticed 4.0.2 got released a few days ago. However, looks like the specs repo wasn't updated with the new version. Would be cool if I could update 😉

**Comment by berkus** [comment]
@Gray-Wind pls.

**Comment by berkus** [comment]
@mitchtreece with "specs repo" you mean cocoapods? because this one is already updated with 4.0.2 (for Carthage).

**Comment by Gray-Wind** [comment]
Pod repo has been updated.
