### ISSUE TITLE
Carthage support for old releases has been removed 

### ISSUE THREAD

**Issue by bwhiteley** [twilio/twilio-chat-ios#23]
Looks like the current version does not support Carthage. That's fine and well, but could you restore Carthage support for older releases? Currently builds are failing because we don't intend to immediately move to the current version, but the Carthage manifests have been removed for older versions. 

Please restore Carthage functionality for older releases. 

Specifically: 
GET https://raw.githubusercontent.com/twilio/twilio-chat-ios/master/twilio-chat-ios.json -> 404

```
*** Downloading binary-only framework twilio-chat-ios at "https://raw.githubusercontent.com/twilio/twilio-chat-ios/master/twilio-chat-ios.json"
Unable to parse binary-only framework JSON at https://raw.githubusercontent.com/twilio/twilio-chat-ios/master/twilio-chat-ios.json due to error: invalid JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Garbage at end." UserInfo={NSDebugDescription=Garbage at end.})))
```

**Comment by Gray-Wind** [comment]
Sorry for that, I've returned back the file.
