### ISSUE TITLE
Artifact of binary target "TwilioChatClient" failed extraction. (SPM)

### ISSUE THREAD

**Issue by alfredomerino** [twilio/twilio-chat-ios#28]
### Description

About a month ago we changed TwilioChat from CocoaPods to SPM. We were having some git lfs annoyances and figured we use SPM since it makes things a little more light weight. Unfortunately, whenever we checkout a branch. We get this issue and can only resolve it by doing a `Reset Package Cache`. 

### Steps to Reproduce

1. Checkout any branch of the project. 
2. Compile 

#### Expected Behavior
The project compiles without the need to `Reset Package Cache`.

#### Actual Behavior
After switching branches project compilation fails with the following error:
`artifact of binary target 'TwilioChatClient' failed extraction: The operation couldn’t be completed. (TSCBasic.StringError error 1.)`

#### Reproduces How Often
100% whenever after switching branch Xcode updates SPM dependencies.

TwilioChatClient - Ver 4.2.1 and Ver. 5.0 

Xcode - 12.5

Similar issue found for `TwilioVideo`: [https://github.com/twilio/twilio-video-ios/issues/190](url)

**Comment by berkus** [comment]
Are you sure this is not a problem with Xcode and SPM?

**Comment by alfredomerino** [comment]
Sorry for the delayed reply. I just downloaded and installed Xcode 13 beta and it looks like the issue is not present there. I had tried using Xcode 12.0 and I believe ver. 11 as well but the issue was present there. I hope this resolves things permanently. Thank you!

**Comment by berkus** [comment]
@alfredomerino great, but do reopen this issue if you still have problems.
