### ISSUE TITLE
TwilioChatClient shutdown crash

### ISSUE THREAD

**Issue by barisozr** [twilio/twilio-chat-ios#29]
Hi,

We're experiencing a crash on shutdown method. Some facts;

- Happens both on device and simulator with iOS 14.5 versions
- Detected firstly on TwilioChatClient 4.2.1 version, then updated to latest (5.0.0) and still have the crash
- App includes TwilioChatClient & TwilioVideo SDK & Socket.IO-Client-Swift SDK

Any help would be appreciated 🙏 

Here's the some logs that may help.
`libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[fir_21121509-4247-416B-8550-7FFE4BF59D4C_TCHWebsocketSessionDelegate _flex_swizzle_3dd34232_URLSession:task:didCompleteWithError:]: unrecognized selector sent to instance 0x600002f70900'
terminating with uncaught exception of type NSException
CoreSimulator 757.5 - Device: iPhone 12 Pro (350306A5-B8F0-4709-85E4-312941C5F992) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 12 Pro`

**Comment by berkus** [comment]
The logs are cut - we require full logs for diagnosing.

**Comment by barisozr** [comment]
Hi again,

We investigated the crash and we may found the reason. In our app, we're also using Flex SDK for debugging. When it's on we're experiencing the crash. So I'm closing for now. Sorry for inconvenience.
