### ISSUE TITLE
TCHClientSynchronizationStatusCompleted requested number of messages

### ISSUE THREAD

**Issue by tomhut** [twilio/twilio-chat-ios#7]
The documentation for TCHClientSynchronizationStatusCompleted notes that "All joined channels, their members and the requested number of messages are synchronized."
Is it possible to specify the 'requested number of messages', perhaps when initializing the client? I had a good look but I couldn't find anything in the docs.

Many thanks in advance.

**Comment by berkus** [comment]
Hi!

The number of messages in all recent SDK versions is 0.

**Comment by tomhut** [comment]
Thanks!
