### ISSUE TITLE
Unzip fails with exit code 9 when trying to install via Carthage

### ISSUE THREAD

**Issue by miktav** [twilio/twilio-chat-ios#8]
I'm getting a strange error when trying to get the Twilio framework via Carthage. This is my Cartfile:

    github "twilio/twilio-chat-ios" 

When I run this command:

    carthage update

I get this error:

`A shell task (/usr/bin/env unzip -uo -qq -d /var/folders/2d/nsdy9h0j0hv0l3p6168k81s80000gp/T/carthage-archive.JoeIDK /Users/miktav/Library/Caches/org.carthage.CarthageKit/binaries/twilio-chat-ios/v2.6.4/ID<Asset>(rawValue:\ 15807865)-TwilioChatClient.framework.zip) failed with exit code 9:
[/Users/miktav/Library/Caches/org.carthage.CarthageKit/binaries/twilio-chat-ios/v2.6.4/ID<Asset>(rawValue: 15807865)-TwilioChatClient.framework.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/miktav/Library/Caches/org.carthage.CarthageKit/binaries/twilio-chat-ios/v2.6.4/ID<Asset>(rawValue: 15807865)-TwilioChatClient.framework.zip or
        /Users/miktav/Library/Caches/org.carthage.CarthageKit/binaries/twilio-chat-ios/v2.6.4/ID<Asset>(rawValue: 15807865)-TwilioChatClient.framework.zip.zip, and cannot find /Users/miktav/Library/Caches/org.carthage.CarthageKit/binaries/twilio-chat-ios/v2.6.4/ID<Asset>(rawValue: 15807865)-TwilioChatClient.framework.zip.ZIP, period.`

I am running Carthage 0.34. I have tried restarting my Mac, putting the Cartfile by itself in a new folder and running the command, deleting derived data in my project, nothing works.

**Comment by miktav** [comment]
I solved this problem by clearing Carthage cache:

    rm -rf ~/Library/Caches/org.carthage.CarthageKit

After this, I ran:

    carthage bootstrap

And the Twilio framework installed successfully.

**Comment by berkus** [comment]
Looks like the file was incompletely downloaded but carthage did not validate that and tried to use it? Might be worth reporting to upstream carthage about this.
