### ISSUE TITLE
"Error instantiating client framework path" when testing code that instantiates TwilioChatClient

### ISSUE THREAD

**Issue by miktav** [twilio/twilio-chat-ios#9]
My app has a class that instantiates a `TwilioChatClient` object. I am unable to test this class from our Tests target. My test fails with:

```
2019-11-15 19:11:59.183529-0800 xctest[53736:2478758] <<<<TwilioChatClient: 0x7fd17fa81be0>>>> -     0x700003426000 | Chat-iOS | Logging initialized
2019-11-15 19:11:59.183673-0800 xctest[53736:2478758] <<<<TwilioChatClient: 0x7fd17fa81be0>>>> -     0x700003426000 | Chat-iOS | Error instantiating client framework path.
2019-11-15 19:11:59.183811-0800 xctest[53736:2478758] <<<<TwilioChatClient: 0x7fd17fa81be0>>>> -     0x700003426000 | Chat-iOS | releasing chat client instance: <TwilioChatClient: 0x7fd17fa81be0>
```

Carthage: `github "twilio/twilio-chat-ios" "v2.6.4"`
Xcode 11.2

This issue is similar to [this one.](https://github.com/twilio/twilio-chat-demo-ios/issues/47)

If I add TwilioChatClient.framework under "Link Binary With Libraries" in my Tests target, my test fails with: 

```
xctest (54616) encountered an error (Failed to load the test bundle. (Underlying error: The bundle “...” couldn’t be loaded because it is damaged or missing necessary resources. The bundle is damaged or missing necessary resources. 
...
  Reason: image not found))
```

**Comment by Gray-Wind** [comment]
Hi, thank you for reaching out.

Firstly, check that you have all setting set properly for your targets.
For your application `Runpath Search Paths` should contain `$(inherited)` and `@executable_path/Frameworks`.
Four your test target `Runpath Search Paths` should contain `$(inherited)`, `@executable_path/Frameworks` and `@loader_path/Frameworks`.

If you will still have this issue, I'll ask you to either give me a sample project with this issue reproducible or send me your current project to investigate the issue. You can send it through DM here or create separate ticket on [Zendesk](https://www.twilio.com/console/support/tickets/create) (do not forget to log in to Twilio page first).

**Comment by miktav** [comment]
Thanks for your reply. Please see sample project here:

[ChatMonkey.zip](https://github.com/twilio/twilio-chat-ios/files/3860836/ChatMonkey.zip)

Please note this is a framework project. You will need to provide a URL to a Programmable Chat Token Twilio function (I didn't include mine for privacy reasons). You will also need to run "carthage bootstrap". 

Then, run the "testMonkey" XCTestCase and it should fail with "Error instantiating client framework path."

**Comment by Gray-Wind** [comment]
In order to test framework, you should add a host application and set this host application in tests' target. Also do not forget to add your actual tests to the host application target and include needed frameworks.

In the end your project might look similar to this:
[ChatMonkey.zip](https://github.com/twilio/twilio-chat-ios/files/3862958/ChatMonkey.zip)

**Comment by miktav** [comment]
@Gray-Wind Thank you! This worked perfectly.

**Comment by sisoje** [comment]
this never works for me

**Comment by Gray-Wind** [comment]
@sisoje could you open new ticket with full information? Also take a look at sample project I fixed previously, maybe solution of your problem is there.

**Comment by sisoje** [comment]
Oh, hi, that was fast :) I didn't want to stress this issue out, as it worked before with CocoaPods, but now we use Carthage and SPM. I want to recheck everything on our side first.

Thank you very much.

**Comment by sisoje** [comment]
i fixed it for now, i added twilio framework to copy files phase in the app target

**Comment by Gray-Wind** [comment]
I'm glad that you solved the issue!
